remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [Java API for JSON Binding (JSON-B)]
description: [JSON-B is a standard binding layer for converting Java objects to/from JSON messages]

links:
  source: https://github.com/eclipse-ee4j/jsonb-api
  #docs: documentation
  javadocs: docs/api/
  download: https://github.com/eclipse-ee4j/jsonb-api/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/jsonb-dev
  #faq: FAQ
